t: &default

  # Credentials for REST APIs

  # Mode can be 'live' or 'sandbox'
  mode: <%= ENV['PAYPAL_MODE'] %>

  <% if ENV['PAYPAL_MODE'] == 'sandbox' %>
  # Credentials for Classic APIs
  app_id: <%= ENV['PAYPAL_SANDBOX_APPID'] %>
  username: <%= ENV['PAYPAL_SANDBOX_USERNAME'] %>
  password: <%= ENV['PAYPAL_SANDBOX_PASSWORD'] %>
  signature: <%= ENV['PAYPAL_SANDBOX_SIGNATURE'] %>
  <% else %>
  app_id: <%= ENV['PAYPAL_LIVE_APPID'] %>
  username: <%= ENV['PAYPAL_LIVE_USERNAME'] %>
  password: <%= ENV['PAYPAL_LIVE_PASSWORD'] %>
  signature: <%= ENV['PAYPAL_LIVE_SIGNATURE'] %>
  <% end %>


  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: sagarwal10-facilitator@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: <%= ENV['PAYPAL_MODE'] %>
